spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://eu-cdbr-west-03.cleardb.net/heroku_cf814242261d1c7?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: bc96f672571aa3
    password: 1d852130
  jackson:
    serialization:
      INDENT_OUTPUT: true

logging:
  level:
    org.springframework.security: debug
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE

security:
  jwt:
    public-key: classpath:public.txt