openapi: 3.0.1
info:
  title: Record Store
  description: Record Store API.
  version: 1.0.0
servers:
- url: /v2
paths:
  /record/all:
    get:
      summary: get all records
      operationId: getAllRecords
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecordResponseOpenApi'
  /format/all:
    get:
      summary: get formats
      operationId: getAllFormats
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FormatResponseOpenApi'
  /format/new:
    post:
      summary: add new format
      operationId: newFormat
      requestBody:
        description: format to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormatResponseOpenApi'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormatResponseOpenApi'
  /book:
    get:
      summary: Get Books
      operationId: getBooks
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    post:
      summary: Add a Book
      operationId: addBook
      requestBody:
        description: Book to be added in shop
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
        required: true
      responses:
        200:
          description: Book Added
          content:
            application/json:
              schema:
                type: string
      x-codegen-request-body-name: book
components:
  schemas:
    RecordResponseOpenApi:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        image:
          type: string
        format:
          $ref: '#/components/schemas/FormatResponseOpenApi'
        units:
          type: integer
    FormatResponseOpenApi:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Book:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          example: Oathbringer
        author:
          type: string
          example: Brandon Sanderson